// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
)

type Querier interface {
	//CreateUser
	//
	//  INSERT INTO users (username, password_hash, salt)
	//  VALUES ($1, $2, $3)
	//  RETURNING id, username, password_hash, salt, created_at, updated_at
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	//GetUserByName
	//
	//  SELECT username, salt, id, password_hash
	//  FROM users
	//  WHERE username = $1
	GetUserByName(ctx context.Context, username string) (GetUserByNameRow, error)
	//InsertTestUser
	//
	//  INSERT INTO users(username, password_hash, salt)
	//  VALUES ('admin', 'asdas', '123123')
	//  RETURNING id, username, password_hash, salt, created_at, updated_at
	InsertTestUser(ctx context.Context) (User, error)
}

var _ Querier = (*Queries)(nil)
