// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/check/v1/check.proto

package checkv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadyCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyCheckReq) Reset() {
	*x = ReadyCheckReq{}
	mi := &file_api_check_v1_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyCheckReq) ProtoMessage() {}

func (x *ReadyCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_check_v1_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyCheckReq.ProtoReflect.Descriptor instead.
func (*ReadyCheckReq) Descriptor() ([]byte, []int) {
	return file_api_check_v1_check_proto_rawDescGZIP(), []int{0}
}

type ReadyCheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyCheckReply) Reset() {
	*x = ReadyCheckReply{}
	mi := &file_api_check_v1_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyCheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyCheckReply) ProtoMessage() {}

func (x *ReadyCheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_check_v1_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyCheckReply.ProtoReflect.Descriptor instead.
func (*ReadyCheckReply) Descriptor() ([]byte, []int) {
	return file_api_check_v1_check_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyCheckReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadyCheckReply) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_api_check_v1_check_proto protoreflect.FileDescriptor

const file_api_check_v1_check_proto_rawDesc = "" +
	"\n" +
	"\x18api/check/v1/check.proto\x12\bcheck.v1\"\x0f\n" +
	"\rReadyCheckReq\"\xa7\x01\n" +
	"\x0fReadyCheckReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12@\n" +
	"\adetails\x18\x02 \x03(\v2&.check.v1.ReadyCheckReply.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012M\n" +
	"\fCheckService\x12=\n" +
	"\x05Ready\x12\x17.check.v1.ReadyCheckReq\x1a\x19.check.v1.ReadyCheckReply\"\x00B\x84\x01\n" +
	"\fcom.check.v1B\n" +
	"CheckProtoP\x01Z'connect-go-example/api/check/v1;checkv1\xa2\x02\x03CXX\xaa\x02\bCheck.V1\xca\x02\bCheck\\V1\xe2\x02\x14Check\\V1\\GPBMetadata\xea\x02\tCheck::V1b\x06proto3"

var (
	file_api_check_v1_check_proto_rawDescOnce sync.Once
	file_api_check_v1_check_proto_rawDescData []byte
)

func file_api_check_v1_check_proto_rawDescGZIP() []byte {
	file_api_check_v1_check_proto_rawDescOnce.Do(func() {
		file_api_check_v1_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_check_v1_check_proto_rawDesc), len(file_api_check_v1_check_proto_rawDesc)))
	})
	return file_api_check_v1_check_proto_rawDescData
}

var (
	file_api_check_v1_check_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
	file_api_check_v1_check_proto_goTypes  = []any{
		(*ReadyCheckReq)(nil),   // 0: check.v1.ReadyCheckReq
		(*ReadyCheckReply)(nil), // 1: check.v1.ReadyCheckReply
		nil,                     // 2: check.v1.ReadyCheckReply.DetailsEntry
	}
)

var file_api_check_v1_check_proto_depIdxs = []int32{
	2, // 0: check.v1.ReadyCheckReply.details:type_name -> check.v1.ReadyCheckReply.DetailsEntry
	0, // 1: check.v1.CheckService.Ready:input_type -> check.v1.ReadyCheckReq
	1, // 2: check.v1.CheckService.Ready:output_type -> check.v1.ReadyCheckReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_check_v1_check_proto_init() }
func file_api_check_v1_check_proto_init() {
	if File_api_check_v1_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_check_v1_check_proto_rawDesc), len(file_api_check_v1_check_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_check_v1_check_proto_goTypes,
		DependencyIndexes: file_api_check_v1_check_proto_depIdxs,
		MessageInfos:      file_api_check_v1_check_proto_msgTypes,
	}.Build()
	File_api_check_v1_check_proto = out.File
	file_api_check_v1_check_proto_goTypes = nil
	file_api_check_v1_check_proto_depIdxs = nil
}
