// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file api/check/v1/check.proto (package check.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/check/v1/check.proto.
 */
export const file_api_check_v1_check: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvY2hlY2svdjEvY2hlY2sucHJvdG8SCGNoZWNrLnYxIg8KDVJlYWR5Q2hlY2tSZXEiigEKD1JlYWR5Q2hlY2tSZXBseRIOCgZzdGF0dXMYASABKAkSNwoHZGV0YWlscxgCIAMoCzImLmNoZWNrLnYxLlJlYWR5Q2hlY2tSZXBseS5EZXRhaWxzRW50cnkaLgoMRGV0YWlsc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEyTQoMQ2hlY2tTZXJ2aWNlEj0KBVJlYWR5EhcuY2hlY2sudjEuUmVhZHlDaGVja1JlcRoZLmNoZWNrLnYxLlJlYWR5Q2hlY2tSZXBseSIAQoQBCgxjb20uY2hlY2sudjFCCkNoZWNrUHJvdG9QAVonY29ubmVjdC1nby1leGFtcGxlL2FwaS9jaGVjay92MTtjaGVja3YxogIDQ1hYqgIIQ2hlY2suVjHKAghDaGVja1xWMeICFENoZWNrXFYxXEdQQk1ldGFkYXRh6gIJQ2hlY2s6OlYxYgZwcm90bzM");

/**
 * @generated from message check.v1.ReadyCheckReq
 */
export type ReadyCheckReq = Message<"check.v1.ReadyCheckReq"> & {
};

/**
 * Describes the message check.v1.ReadyCheckReq.
 * Use `create(ReadyCheckReqSchema)` to create a new message.
 */
export const ReadyCheckReqSchema: GenMessage<ReadyCheckReq> = /*@__PURE__*/
  messageDesc(file_api_check_v1_check, 0);

/**
 * @generated from message check.v1.ReadyCheckReply
 */
export type ReadyCheckReply = Message<"check.v1.ReadyCheckReply"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;

  /**
   * @generated from field: map<string, string> details = 2;
   */
  details: { [key: string]: string };
};

/**
 * Describes the message check.v1.ReadyCheckReply.
 * Use `create(ReadyCheckReplySchema)` to create a new message.
 */
export const ReadyCheckReplySchema: GenMessage<ReadyCheckReply> = /*@__PURE__*/
  messageDesc(file_api_check_v1_check, 1);

/**
 * @generated from service check.v1.CheckService
 */
export const CheckService: GenService<{
  /**
   * @generated from rpc check.v1.CheckService.Ready
   */
  ready: {
    methodKind: "unary";
    input: typeof ReadyCheckReqSchema;
    output: typeof ReadyCheckReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_check_v1_check, 0);

