services:

  postgres17:
    image: postgres:18rc1-alpine3.22
    container_name: postgres18
#    platform: linux/amd64
    restart: on-failure:5
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
#    networks:
#      app-network:

volumes:
  data:

#networks:
#  app-network:
#    external: true
