// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/greet/v1/greet.proto

package greetv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Salt          string                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_greet_v1_greet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_v1_greet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_greet_v1_greet_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_greet_v1_greet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_v1_greet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_greet_v1_greet_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AuthChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallengeRequest) Reset() {
	*x = AuthChallengeRequest{}
	mi := &file_api_greet_v1_greet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallengeRequest) ProtoMessage() {}

func (x *AuthChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_v1_greet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallengeRequest.ProtoReflect.Descriptor instead.
func (*AuthChallengeRequest) Descriptor() ([]byte, []int) {
	return file_api_greet_v1_greet_proto_rawDescGZIP(), []int{2}
}

func (x *AuthChallengeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AuthChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     string                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Salt          string                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallengeResponse) Reset() {
	*x = AuthChallengeResponse{}
	mi := &file_api_greet_v1_greet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallengeResponse) ProtoMessage() {}

func (x *AuthChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_v1_greet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallengeResponse.ProtoReflect.Descriptor instead.
func (*AuthChallengeResponse) Descriptor() ([]byte, []int) {
	return file_api_greet_v1_greet_proto_rawDescGZIP(), []int{3}
}

func (x *AuthChallengeResponse) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *AuthChallengeResponse) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

type SubmitAuthRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Username          string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	HashedCredential  string                 `protobuf:"bytes,2,opt,name=hashed_credential,json=hashedCredential,proto3" json:"hashed_credential,omitempty"`    // 客户端使用密码 + salt 哈希后的凭证
	AuthRequestId     string                 `protobuf:"bytes,3,opt,name=auth_request_id,json=authRequestId,proto3" json:"auth_request_id,omitempty"`           // 链路追踪
	ChallengeResponse string                 `protobuf:"bytes,4,opt,name=challenge_response,json=challengeResponse,proto3" json:"challenge_response,omitempty"` // 客户端对挑战的响应
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubmitAuthRequest) Reset() {
	*x = SubmitAuthRequest{}
	mi := &file_api_greet_v1_greet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAuthRequest) ProtoMessage() {}

func (x *SubmitAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_v1_greet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAuthRequest.ProtoReflect.Descriptor instead.
func (*SubmitAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_greet_v1_greet_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SubmitAuthRequest) GetHashedCredential() string {
	if x != nil {
		return x.HashedCredential
	}
	return ""
}

func (x *SubmitAuthRequest) GetAuthRequestId() string {
	if x != nil {
		return x.AuthRequestId
	}
	return ""
}

func (x *SubmitAuthRequest) GetChallengeResponse() string {
	if x != nil {
		return x.ChallengeResponse
	}
	return ""
}

type SubmitAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // jwt令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAuthResponse) Reset() {
	*x = SubmitAuthResponse{}
	mi := &file_api_greet_v1_greet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAuthResponse) ProtoMessage() {}

func (x *SubmitAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_greet_v1_greet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAuthResponse.ProtoReflect.Descriptor instead.
func (*SubmitAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_greet_v1_greet_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitAuthResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SubmitAuthResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SubmitAuthResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

var File_api_greet_v1_greet_proto protoreflect.FileDescriptor

const file_api_greet_v1_greet_proto_rawDesc = "" +
	"\n" +
	"\x18api/greet/v1/greet.proto\x12\bgreet.v1\"|\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\tR\x04salt\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\x14AuthChallengeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"I\n" +
	"\x15AuthChallengeResponse\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\tR\tchallenge\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\tR\x04salt\"\xb3\x01\n" +
	"\x11SubmitAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12+\n" +
	"\x11hashed_credential\x18\x02 \x01(\tR\x10hashedCredential\x12&\n" +
	"\x0fauth_request_id\x18\x03 \x01(\tR\rauthRequestId\x12-\n" +
	"\x12challenge_response\x18\x04 \x01(\tR\x11challengeResponse\"]\n" +
	"\x12SubmitAuthResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken2\xf5\x01\n" +
	"\fGreetService\x12C\n" +
	"\bRegister\x12\x19.greet.v1.RegisterRequest\x1a\x1a.greet.v1.RegisterResponse\"\x00\x12U\n" +
	"\x10GetAuthChallenge\x12\x1e.greet.v1.AuthChallengeRequest\x1a\x1f.greet.v1.AuthChallengeResponse\"\x00\x12I\n" +
	"\n" +
	"SubmitAuth\x12\x1b.greet.v1.SubmitAuthRequest\x1a\x1c.greet.v1.SubmitAuthResponse\"\x00B\x84\x01\n" +
	"\fcom.greet.v1B\n" +
	"GreetProtoP\x01Z'connect-go-example/api/greet/v1;greetv1\xa2\x02\x03GXX\xaa\x02\bGreet.V1\xca\x02\bGreet\\V1\xe2\x02\x14Greet\\V1\\GPBMetadata\xea\x02\tGreet::V1b\x06proto3"

var (
	file_api_greet_v1_greet_proto_rawDescOnce sync.Once
	file_api_greet_v1_greet_proto_rawDescData []byte
)

func file_api_greet_v1_greet_proto_rawDescGZIP() []byte {
	file_api_greet_v1_greet_proto_rawDescOnce.Do(func() {
		file_api_greet_v1_greet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_greet_v1_greet_proto_rawDesc), len(file_api_greet_v1_greet_proto_rawDesc)))
	})
	return file_api_greet_v1_greet_proto_rawDescData
}

var (
	file_api_greet_v1_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
	file_api_greet_v1_greet_proto_goTypes  = []any{
		(*RegisterRequest)(nil),       // 0: greet.v1.RegisterRequest
		(*RegisterResponse)(nil),      // 1: greet.v1.RegisterResponse
		(*AuthChallengeRequest)(nil),  // 2: greet.v1.AuthChallengeRequest
		(*AuthChallengeResponse)(nil), // 3: greet.v1.AuthChallengeResponse
		(*SubmitAuthRequest)(nil),     // 4: greet.v1.SubmitAuthRequest
		(*SubmitAuthResponse)(nil),    // 5: greet.v1.SubmitAuthResponse
	}
)

var file_api_greet_v1_greet_proto_depIdxs = []int32{
	0, // 0: greet.v1.GreetService.Register:input_type -> greet.v1.RegisterRequest
	2, // 1: greet.v1.GreetService.GetAuthChallenge:input_type -> greet.v1.AuthChallengeRequest
	4, // 2: greet.v1.GreetService.SubmitAuth:input_type -> greet.v1.SubmitAuthRequest
	1, // 3: greet.v1.GreetService.Register:output_type -> greet.v1.RegisterResponse
	3, // 4: greet.v1.GreetService.GetAuthChallenge:output_type -> greet.v1.AuthChallengeResponse
	5, // 5: greet.v1.GreetService.SubmitAuth:output_type -> greet.v1.SubmitAuthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_greet_v1_greet_proto_init() }
func file_api_greet_v1_greet_proto_init() {
	if File_api_greet_v1_greet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_greet_v1_greet_proto_rawDesc), len(file_api_greet_v1_greet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_greet_v1_greet_proto_goTypes,
		DependencyIndexes: file_api_greet_v1_greet_proto_depIdxs,
		MessageInfos:      file_api_greet_v1_greet_proto_msgTypes,
	}.Build()
	File_api_greet_v1_greet_proto = out.File
	file_api_greet_v1_greet_proto_goTypes = nil
	file_api_greet_v1_greet_proto_depIdxs = nil
}
