// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file api/greet/v1/greet.proto (package greet.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/greet/v1/greet.proto.
 */
export const file_api_greet_v1_greet: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvZ3JlZXQvdjEvZ3JlZXQucHJvdG8SCGdyZWV0LnYxIlcKD1JlZ2lzdGVyUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIVCg1wYXNzd29yZF9oYXNoGAIgASgJEg0KBWVtYWlsGAMgASgJEgwKBHNhbHQYBCABKAkiIwoQUmVnaXN0ZXJSZXNwb25zZRIPCgd1c2VyX2lkGAEgASgJIigKFEF1dGhDaGFsbGVuZ2VSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJIjgKFUF1dGhDaGFsbGVuZ2VSZXNwb25zZRIRCgljaGFsbGVuZ2UYASABKAkSDAoEc2FsdBgCIAEoCSJ1ChFTdWJtaXRBdXRoUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIZChFoYXNoZWRfY3JlZGVudGlhbBgCIAEoCRIXCg9hdXRoX3JlcXVlc3RfaWQYAyABKAkSGgoSY2hhbGxlbmdlX3Jlc3BvbnNlGAQgASgJIkUKElN1Ym1pdEF1dGhSZXNwb25zZRIMCgRjb2RlGAEgASgJEg0KBXN0YXRlGAIgASgJEhIKCmF1dGhfdG9rZW4YAyABKAky9QEKDEdyZWV0U2VydmljZRJDCghSZWdpc3RlchIZLmdyZWV0LnYxLlJlZ2lzdGVyUmVxdWVzdBoaLmdyZWV0LnYxLlJlZ2lzdGVyUmVzcG9uc2UiABJVChBHZXRBdXRoQ2hhbGxlbmdlEh4uZ3JlZXQudjEuQXV0aENoYWxsZW5nZVJlcXVlc3QaHy5ncmVldC52MS5BdXRoQ2hhbGxlbmdlUmVzcG9uc2UiABJJCgpTdWJtaXRBdXRoEhsuZ3JlZXQudjEuU3VibWl0QXV0aFJlcXVlc3QaHC5ncmVldC52MS5TdWJtaXRBdXRoUmVzcG9uc2UiAEKEAQoMY29tLmdyZWV0LnYxQgpHcmVldFByb3RvUAFaJ2Nvbm5lY3QtZ28tZXhhbXBsZS9hcGkvZ3JlZXQvdjE7Z3JlZXR2MaICA0dYWKoCCEdyZWV0LlYxygIIR3JlZXRcVjHiAhRHcmVldFxWMVxHUEJNZXRhZGF0YeoCCUdyZWV0OjpWMWIGcHJvdG8z");

/**
 * @generated from message greet.v1.RegisterRequest
 */
export type RegisterRequest = Message<"greet.v1.RegisterRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password_hash = 2;
   */
  passwordHash: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string salt = 4;
   */
  salt: string;
};

/**
 * Describes the message greet.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_api_greet_v1_greet, 0);

/**
 * @generated from message greet.v1.RegisterResponse
 */
export type RegisterResponse = Message<"greet.v1.RegisterResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message greet.v1.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_api_greet_v1_greet, 1);

/**
 * @generated from message greet.v1.AuthChallengeRequest
 */
export type AuthChallengeRequest = Message<"greet.v1.AuthChallengeRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message greet.v1.AuthChallengeRequest.
 * Use `create(AuthChallengeRequestSchema)` to create a new message.
 */
export const AuthChallengeRequestSchema: GenMessage<AuthChallengeRequest> = /*@__PURE__*/
  messageDesc(file_api_greet_v1_greet, 2);

/**
 * @generated from message greet.v1.AuthChallengeResponse
 */
export type AuthChallengeResponse = Message<"greet.v1.AuthChallengeResponse"> & {
  /**
   * @generated from field: string challenge = 1;
   */
  challenge: string;

  /**
   * @generated from field: string salt = 2;
   */
  salt: string;
};

/**
 * Describes the message greet.v1.AuthChallengeResponse.
 * Use `create(AuthChallengeResponseSchema)` to create a new message.
 */
export const AuthChallengeResponseSchema: GenMessage<AuthChallengeResponse> = /*@__PURE__*/
  messageDesc(file_api_greet_v1_greet, 3);

/**
 * @generated from message greet.v1.SubmitAuthRequest
 */
export type SubmitAuthRequest = Message<"greet.v1.SubmitAuthRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * 客户端使用密码 + salt 哈希后的凭证
   *
   * @generated from field: string hashed_credential = 2;
   */
  hashedCredential: string;

  /**
   * 链路追踪
   *
   * @generated from field: string auth_request_id = 3;
   */
  authRequestId: string;

  /**
   * 客户端对挑战的响应
   *
   * @generated from field: string challenge_response = 4;
   */
  challengeResponse: string;
};

/**
 * Describes the message greet.v1.SubmitAuthRequest.
 * Use `create(SubmitAuthRequestSchema)` to create a new message.
 */
export const SubmitAuthRequestSchema: GenMessage<SubmitAuthRequest> = /*@__PURE__*/
  messageDesc(file_api_greet_v1_greet, 4);

/**
 * @generated from message greet.v1.SubmitAuthResponse
 */
export type SubmitAuthResponse = Message<"greet.v1.SubmitAuthResponse"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string state = 2;
   */
  state: string;

  /**
   * jwt令牌
   *
   * @generated from field: string auth_token = 3;
   */
  authToken: string;
};

/**
 * Describes the message greet.v1.SubmitAuthResponse.
 * Use `create(SubmitAuthResponseSchema)` to create a new message.
 */
export const SubmitAuthResponseSchema: GenMessage<SubmitAuthResponse> = /*@__PURE__*/
  messageDesc(file_api_greet_v1_greet, 5);

/**
 * @generated from service greet.v1.GreetService
 */
export const GreetService: GenService<{
  /**
   * @generated from rpc greet.v1.GreetService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * @generated from rpc greet.v1.GreetService.GetAuthChallenge
   */
  getAuthChallenge: {
    methodKind: "unary";
    input: typeof AuthChallengeRequestSchema;
    output: typeof AuthChallengeResponseSchema;
  },
  /**
   * @generated from rpc greet.v1.GreetService.SubmitAuth
   */
  submitAuth: {
    methodKind: "unary";
    input: typeof SubmitAuthRequestSchema;
    output: typeof SubmitAuthResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_greet_v1_greet, 0);

