// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAuthData():Promise<main.AuthData>;

export function Greet(arg1:string):Promise<string>;

export function Logout():Promise<void>;

export function OpenLoginPage():Promise<void>;
