name: Build

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

# 共享环境变量
env:
  REGISTRY: harbor.apikv.com:5443
  REGISTER_USER: sumery
  DOCKER_USER: lookeke
  IMAGE_NAME: connect-example-backend
  VERSION: ${{ github.event.workflow_run.head_branch }}
  GOOS: linux
  GOARCH: arm64
  GO_IMAGE: golang:1.25.1-alpine3.22
  GO_PROXY: https://proxy.golang.org
  CGO_ENABLED: 0

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && startsWith(github.event.workflow_run.head_branch, 'v') }}
    steps:
      - run: echo 'The triggering workflow failed'
  on-success:
    runs-on: ubuntu-24.04-arm
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') }}
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
          check-latest: true
          cache-dependency-path: '**/go.sum'

        # 注意：这里保持默认检出，不需要特殊 ref main

#      只有需要构建跨平台才使用
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # 用户名, 这里是上下文自动使用触发工作流运行的用户的用户名
          password: ${{ secrets.MANIFEST_REPO_PAT }}

      - name: Login to Private Registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ env.REGISTRY }} --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

#      - name: Build, Tag and Push OCI Image
#        # 移除缓存步骤，简化；如果需要保留，请重新添加
#        run: |
#          docker build . -t actions/${{ env.IMAGE_NAME }} \
#            --build-arg GO_PROXY=$GO_PROXY \
#            --build-arg GOIMAGE=$GO_IMAGE \
#            --build-arg CGOENABLED=$CGO_ENABLED \
#            --build-arg VERSION=${{ env.VERSION }} \
#            --build-arg GOOS=$GOOS \
#            --build-arg GOARCH=$GOARCH \
#            --build-arg SERVICE=server
#
#          docker tag actions/${{ env.IMAGE_NAME }} ${{ env.REGISTRY }}/${{ env.REGISTER_USER }}/${{ env.IMAGE_NAME }}:$VERSION
#          docker push ${{ env.REGISTRY }}/${REGISTER_USER}/${{ env.IMAGE_NAME }}:$VERSION
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha,scope=go-backend-build
          cache-to: type=gha,scope=go-backend-build,mode=max
          build-args:
            GO_PROXY=${{ env.GO_PROXY }}
            GOIMAGE=${{ env.GO_IMAGE }}
            CGOENABLED=${{ env.CGO_ENABLED }}
            VERSION=${{ env.VERSION }}
            GOOS=${{ env.GOOS }}
            GOARCH=${{ env.GOARCH }}
            SERVICE=server
          tags: |
            ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
#
#      # 如果 CI 成功, 触发下一个 CD Workflow
#      - name: Notify CD Workflow
#        run: echo "BUILD_SUCCESS=true" >> $GITHUB_ENV
