name: CI Backend Build

on:
  push:
    tags:
      - 'v*.*.*'

# 共享环境变量
env:
  REGISTRY: harbor.apikv.com:5443
  REGISTER_USER: sumery
  VERSION: ${{ github.ref_name }}
  GOOS: linux
  GOARCH: arm64
  GO_IMAGE: golang:1.25.1-alpine3.22
  GO_PROXY: https://proxy.golang.org
  CGO_ENABLED: 0

jobs:
  backend-test:
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
          check-latest: true
          cache-dependency-path: '**/go.sum'

      - name: Run Go tests
        run: go test -short -coverprofile=coverage.out ./...

  backend-build:
    needs: backend-test
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        service_config:
          - { service: connect-example-backend }
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        # 注意：这里保持默认检出，不需要特殊 ref main

      - name: Set up Docker Buildx and QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to OCI Registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ env.REGISTRY }} --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build, Tag and Push OCI Image
        # 移除缓存步骤，简化；如果需要保留，请重新添加
        run: |
          docker build . -t actions/${{ matrix.service_config.service }} \
            --build-arg GO_PROXY=$GO_PROXY \
            --build-arg GOIMAGE=$GO_IMAGE \
            --build-arg CGOENABLED=$CGO_ENABLED \
            --build-arg VERSION=${{ env.VERSION }} \
            --build-arg GOOS=$GOOS \
            --build-arg GOARCH=$GOARCH \
            --build-arg SERVICE=server

          docker tag actions/${{ matrix.service_config.service }} ${{ env.REGISTRY }}/${{ env.REGISTER_USER }}/${{ matrix.service_config.service }}:$VERSION
          docker push ${{ env.REGISTRY }}/${REGISTER_USER}/${{ matrix.service_config.service }}:$VERSION

      # 如果 CI 成功, 触发下一个 CD Workflow
      - name: Notify CD Workflow
        run: echo "BUILD_SUCCESS=true" >> $GITHUB_ENV
